### ISSUE TITLE
Enable es2015 modules feature

### ISSUE THREAD

**Issue by Alphapage** [nodejs/node-chakracore#212]
Hello,

I can't find a way to enable es2015 modules in node-chakracore.
Is it possible to play with such a feature since chakracore support it (special command line arg) ?

Thank you in advance for your answers.

**Comment by boingoing** [comment]
Hi @Alphapage, thanks for your question.

Technically, es2015 modules are supported by chakracore but you can't use them in node-chakracore since node itself doesn't have a story for supporting es2015 modules, yet. There is some discussion happening around this feature and you could play around with it by implementing some of the needed pieces. See (https://github.com/nodejs/node/issues/8866#issuecomment-270822697).

It is possible to use es2015 modules with chakracore via our test host `ch` if you want to play around outside of node proper. Try to use `WScript.LoadModuleFile(filename)` or `WScript.LoadScriptFile(filename, "module")`.
