### ISSUE TITLE
asm.js and WebAssembly support

### ISSUE THREAD

**Issue by JoeUX** [nodejs/node-chakracore#234]
Version: Node 7.10.0
Platform: Windows 10 Home and Pro, 64-bit, Version 1703
IDE: Visual Studio 2017

Hi all – Does node-ChakraCore include the asm.js and WebAssembly support that Chakra has in Edge?

If yes, I'd be grateful if you could point me to some tips or docs on how to leverage those features on a server.

Thanks.

**Comment by Cellule** [comment]
Node-ChakraCore has all the asm.js capabilities that Edge has.
As for WebAssembly, the feature is currently turned off by default.
You can follow up with https://github.com/Microsoft/ChakraCore/pull/2447.

It might be possible to try out WebAssembly in Node-ChakraCore, but you would need to build it yourself since the configuration flags are unavailable in Release builds.
I can't see if there is any support for Test builds in node-chakracore, maybe @digitalinfinity can answer this if you want to go down that route.

Debug build would work anyway (although not very great to try a feature out).
In order to turn WebAssembly on, you need a file named `jscript.config` next to chakracore.dll and in the file put
```
-wasm
```

If you are able to wait it out a little longer, once we turn WebAssembly on by default, you would be able to use it in Node-ChakraCore no problem :)

**Comment by Cellule** [comment]
WebAssembly is now available in Node-ChakraCore release builds.

**Comment by digitalinfinity** [comment]
Thanks @Cellule- closing this one, @JoeUX let us know if you need any more information.

**Comment by JoeUX** [comment]
Thanks for the heads-up @Cellule.
