### ISSUE TITLE
Skip flaky tests by default?

### ISSUE THREAD

**Issue by obastemur** [nodejs/node-chakracore#426]
`make test` might skip flaky tests by default.

- If I'm interested with flaky tests, well, I might use an extra argument to include them?
- Flaky tests are creating unexpected / unwanted results and also affecting dev mechine. (hanging process?)

**Comment by digitalinfinity** [comment]
@joaocgreis @Trott I've often wondered about this- what is the philosophy between flaky and skip? I think @joaocgreis might have explained it to me once though 😄 

I think the question here is, if ChakraCore is known to fail certain tests due to features that we've yet to implement, should we skip those tests or let them run but ignore the results. In the latter case, as @obastemur mentions, there could be some side-effects like zombie processes that make for an unpleasant developer experience

**Comment by Trott** [comment]
If you wish to skip tests, you can mark them as `SKIP` in the `.status` file. That will skip with `make test` and `make test-ci`.

I would not mark such a test as flaky because flaky implies that the test *should* pass and something is wrong such that it *sometimes* doesn't pass.

I can only guess at the philosophy around the flaky tests feature. I *think* it pre-dates me (but maybe not). But this sounds like a use case for `SKIP` to me which is already implemented the way it would be needed for this use case. You'd implement it the same way you would a flaky test, but instead of putting `PASS,FLAKY` in the `.status` file, you put `SKIP` there.

**Comment by joaocgreis** [comment]
This was discussed in https://github.com/nodejs/node-chakracore/pull/233 (and some conversations leading to that PR), the relevant part is:

>Tests that have issues with ChakraCore should fall in one of two categories:
>- Tests that are V8 specific: Should be skipped in the beginning of the test code with `common.skip()` (this allows the build to be green).
>- Tests that are not _yet_ working with ChakraCore, but should in the future: should be marked as flaky in the status files (this makes the build yellow, so that these tests are not forgotten).

There might be a third: tests that break the test runner can be marked as SKIP in the status files.

Having flaky tests in Node-ChakraCore is a little different from Node-V8, there are many more and will likely be around for much longer. But the meaning is the same: they should work but currently don't. I think they are a good reminder that some things still need some work, but of course this can always be reevaluated if you think the time is right.

One easy thing to do to skip them locally: `export FLAKY_TESTS=skip` before running `make`.

**Comment by obastemur** [comment]
> so that these tests are not forgotten

> One easy thing to do to skip them locally: export FLAKY_TESTS=skip before running make

Second one much easier to forget for me.. If I'm supposed to remember one or another, I prefer neither and open issues for failing tests instead.

call me approaching this wrong but I expect `make test` is to show if things are okay with my changes.. not to remind me `flaky` tests.

**Comment by joaocgreis** [comment]
We can mark all tests that are not yet working with SKIP instead of FLAKY, that way we keep the distinction between tests that should and tests that won't ever work. But with this there'd be no way to run those tests without changing the status files.

Or change the default in the [Makefile](https://github.com/nodejs/node-chakracore/blob/00702bb1ed6c1c7dfac4c156512b47a557555032/Makefile#L8) and [test.py](https://github.com/nodejs/node-chakracore/blob/00702bb1ed6c1c7dfac4c156512b47a557555032/tools/test.py#L1400), but that would mean floating another patch.

@nodejs/node-chakracore which option looks better to you?

**Comment by jackhorton** [comment]
I think we have a number of "flaky" tests that fail due to timeout where we would be better off simply skipping those, because our tests take a _very_ long time to run as a result. I think a good bound for these could be:

1. PASS,FLAKY for tests that really actually do fail sporadically due to timing or OS issues (basically, tests that we think should work right now but don't)
2. common.skip for tests that are not currently supported by Node-ChakraCore but should be in the future (this fits with the fact that we already modify tests with `if (common.isChakraEngine)` when very specific parts of a test aren't supported)
3. PASS,SKIP for tests that will never work on Node-ChakraCore because they test something we know we will never support.

To be honest, I didn't know that PASS,SKIP existed. One possible reason to swap the usage of PASS,SKIP and common.skip that I give above is what happens when a test uses syntax features that we don't support at all/in the context of node, such as ES modules.

EDIT: given such a plan, we would probably convert the majority of our PASS,FLAKY tests to skips. As far as I know, there are very few that are flaky for us in the same way that node upstream uses the term.
